src/OrderBundle/Entity/Cart.php
<?php

namespace OrderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Cart
 *
 * @ORM\Table(name="cart")
 * @ORM\Entity(repositoryClass="OrderBundle\Repository\CartRepository")
 */
class Cart
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="date", type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(name="status", type="smallint")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", cascade={"persist"})
     */
    private $owner;

    /**
     * @ORM\ManyToOne(targetEntity="RestaurantBundle\Entity\Restaurant", cascade={"persist"})
     */
    private $restaurant;

    /**
     * @ORM\ManyToMany(targetEntity="RestaurantBundle\Entity\Recipe")
     * @ORM\JoinColumn(name="cart_recip")
     */
    protected $recipes;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set owner.
     *
     * @param \UserBundle\Entity\User|null $owner
     *
     * @return Cart
     */
    public function setOwner(\UserBundle\Entity\User $owner = null)
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Get owner.
     *
     * @return \UserBundle\Entity\User|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Set restaurant.
     *
     * @param \RestaurantBundle\Entity\Restaurant|null $restaurant
     *
     * @return Cart
     */
    public function setRestaurant(\RestaurantBundle\Entity\Restaurant $restaurant = null)
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    /**
     * Get restaurant.
     *
     * @return \RestaurantBundle\Entity\Restaurant|null
     */
    public function getRestaurant()
    {
        return $this->restaurant;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->recipes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add recipe.
     *
     * @param \RestaurantBundle\Entity\Recipe $recipe
     *
     * @return Cart
     */
    public function addRecipe(\RestaurantBundle\Entity\Recipe $recipe)
    {
        $this->recipes[] = $recipe;

        return $this;
    }

    /**
     * Remove recipe.
     *
     * @param \RestaurantBundle\Entity\Recipe $recipe
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeRecipe(\RestaurantBundle\Entity\Recipe $recipe)
    {
        return $this->recipes->removeElement($recipe);
    }

    /**
     * Get recipes.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRecipes()
    {
        return $this->recipes;
    }

    /**
     * returns the total cost of every product in the cart
     *
     * @return  int
     */
    public function getTotalPrice()
    {
        $total = 0;

        foreach ($this->recipes as $recipe){
            $total += $recipe->getPrice();
        }

        return $total;
    }

    /**
     * Set date.
     *
     * @param \DateTime|null $date
     *
     * @return Cart
     */
    public function setDate($date = null)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date.
     *
     * @return \DateTime|null
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return Cart
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }
}

src/OrderBundle/Resources/views/checkout.html.twig
{% extends '@BigFood/layout.html.twig' %}

{% block title %}
    Proceed to checkout
{% endblock %}

{% block body %}
    <h1 class="text-center">Order your food now !</h1>
    <br>
    {% if cart is defined and cart is not empty %}
    <p class="text-center">From {{ cart.restaurant.name }}</p>
    <br>
        <div class="table-responsive">
            <table class="table text-left">
                <tr class="thead-light">
                    <th colspan="4">Your order</th>
                </tr>
                {% for recipe in cart.recipes %}
                    <tr class="table-hover">
                        <td>{{ recipe.name }}</td>
                        <td class="font-italic text-secondary">{{ recipe.description }}</td>
                        <td class="font-italic text-secondary">{{ recipe.price }} €</td>
                        <td><a href="{{ path('remove_from_cart', {'recipe': recipe.id, 'cart': cart.id}) }}" class="btn btn-danger btn-block" title="Remove from cart"><i class="fas fa-times"></i></a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" class="font-weight-bold">TOTAL :</td>
                    <td class="font-weight-bold">{{ cart.getTotalPrice }} €</td>
                    <td><a href="{{ path('proceed_checkout', {'id': cart.id}) }}" class="btn btn-info btn-block" title="Order"><i class="fas fa-cart-arrow-down"></i></a></td>
                </tr>
            </table>
        </div>
    {% else %}
        <p class="text-center">Your cart is empty !</p>
    {% endif %}
{% endblock %}

src/OrderBundle/Resources/views/manage_orders.html.twig
{% extends '@BigFood/layout.html.twig' %}

{% block title %}
    Manage Orders
{% endblock %}

{% block body %}
    <h1 class="text-center">Manage orders to {{ restaurant.name }}</h1>
    <br>
    {% if carts is not empty %}
        <div class="table-responsive">
            <table class="table table-hover text-left">
                <thead>
                    <tr class="thead-light">
                        <th>Date</th>
                        <th>Username</th>
                        <th>Order</th>
                        <th>Price</th>
                        <th>Picked-up ?</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart in carts %}
                        <tr>
                            <td>{{ cart.date|date("d/m/Y - H:i") }}</td>
                            <td>{{ cart.owner.username }}</td>
                            <td>
                                <ul class="list-group">
                                    {% for recipe in cart.recipes %}
                                        <li>{{ recipe.name }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>{{ cart.totalPrice }}€</td>
                            <td><a class="btn btn-info" href="{{ path('archive_order', {'id': cart.id}) }}" title="Archive"><i class="fas fa-file-archive"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p class="text-center">No pending orders</p>
    {% endif %}
{% endblock %}